# Numpy:
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [2]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

## Create array using numpy
## Creating 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [7]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [23]:
# 2 D Array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr2)
arr2.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


(3, 5)

In [18]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [21]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
arr=np.array([[1,2,3],[4,5,6]])

print("Array - ", arr)
print("Shape - ", arr.shape)
print("Number of Dimensions - ", arr.ndim)
print("Size - ", arr.size)
print("data Type - ", arr.dtype)


Array -  [[1 2 3]
 [4 5 6]]
Shape -  (2, 3)
Number of Dimensions -  2
Size -  6
data Type -  int64


In [37]:
## Numpy Vectorized Operations
arr1=np.array([[1,2,3,4,5]])
arr2=np.array([[10,20,30,40,50]])

print("Addition - ", arr1+arr2)
print("Subtraction - ", arr2-arr1)
print("Multiplication - ", arr2*arr1)
print("Division - ", arr2 / arr1)

Addition -  [[11 22 33 44 55]]
Subtraction -  [[ 9 18 27 36 45]]
Multiplication -  [[ 10  40  90 160 250]]
Division -  [[10. 10. 10. 10. 10.]]


In [39]:
# Universal Functions
arr=np.array([[1,2,3,4,5]])

## Square Root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))


[[1.         1.41421356 1.73205081 2.         2.23606798]]
[[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]]


In [40]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [47]:
## Slicing
print(arr2[1:,0:2])
arr2.shape

[[ 6  7]
 [11 12]]


(3, 5)

In [50]:
print(arr2)
print(arr2[1:2,0:1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[6]]


In [54]:
print(arr2[1:2,0])

[6]


In [55]:
arr2[1:2,2]=100
print(arr2)

[[  1   2   3   4   5]
 [  6   7 100   9  10]
 [ 11  12  13  14  15]]


In [56]:
arr2[1:]=100
print(arr2)

[[  1   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [63]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])